baseURL = "https://sagikazarmark.github.io/mater/"
languageCode = "en"
title = "Mater"

theme = "self"

[params]
    description = "Hugo theme based on Materialize CSS."
    author = "Márk Sági-Kazár"

    [params.header]
        color = "light-blue lighten-1"

    [params.docs.header]
        color = "light-blue"
        subtextColor = ""

    [params.docs.menu]
        activeColor = "light-blue"

[[menu.main]]
    name = "Github"
    url = "https://github.com/sagikazarmark/mater"
    weight = -200

[[menu.docs]]
    name = "Home"
    url = "/"
    weight = -210

[[menu.docs]]
    name = "Templates"
    identifier = "templates"

[[menu.docs]]
    name = "Shortcodes"
    identifier = "shortcodes"
