# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Mater"
license = "MIT"
#licenselink = "https://github.com/sagikazarmark/mater/blob/master/LICENSE"
description = "Hugo theme based on Materialize CSS"
homepage = "https://sagikazarmark.github.io/mater"
tags = []
features = []
min_version = "0.20"

[author]
    name = "Márk Sági-Kazár"
    homepage = "https://sagikazarmark.hu"
